test:
  sessions:
    default:
      database: pioneer_test
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: pioneer
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: pioneer
      hosts:
        - localhost:27017
